#include <iostream>

int main()
{
    std::cout << "####### ###" << std::endl;
    std::cout << "Problem 002" << std::endl;
    std::cout << "####### ###" << std::endl;
    std::cout << std::endl;
    std::cout << "\t---- --------- -------" << std::endl;
    std::cout << "\tEven Fibonacci numbers" << std::endl;
    std::cout << "\t---- --------- -------" << std::endl;
    std::cout << std::endl;
    std::cout << "\t\tEach new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:" << std::endl;
    std::cout << "\t\t\t\t1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ..." << std::endl;
    std::cout << "\t\tBy considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms." << std::endl;
    std::cout << std::endl;

    float answer{0};

    //YOUR CODE HERE

    std::cout << "ANSWER: " << answer << std::endl;

    return 0;
}